# Columns that represent outputs for weighting
WEIGHTABLE_COLUMNS = [
    "forge_points",
    "forgepoint_package",
    "coins",
    "supplies",
    "medals",
    "goods",
    "next_age_goods",
    "prev_age_goods",
    "special_goods",
    "guild_goods",
    "rogues",
    "fast_units",
    "heavy_units",
    "ranged_units",
    "artillery_units",
    "light_units",
    "next_age_fast_units",
    "next_age_heavy_units",
    "next_age_ranged_units",
    "next_age_artillery_units",
    "next_age_light_units",
    "Population",
    "Red Attack",
    "Red Defense",
    "Blue Attack",
    "Blue Defense",
    "Red GBG Attack",
    "Red GBG Defense",
    "Blue GBG Attack",
    "Blue GBG Defense",
    "Red GE Attack",
    "Red GE Defense",
    "Blue GE Attack",
    "Blue GE Defense",
    "Red QI Attack",
    "Red QI Defense",
    "Blue QI Attack",
    "Blue QI Defense",
    "QI Coin at start",
    "QI Supplies at start",
    "QI Goods at start",
    "QI Units at start",
    "QA per hour",
    "QA Capacity",
    "finish_special_production",
    "Coin %",
    "Supplies %",
    "Medal Boost",
]

# Additive metrics
ADDITIVE_METRICS = [
    "coins",
    "supplies",
    "medals",
    "forge_points",
    "forgepoint_package",
    "goods",
    "next_age_goods",
    "prev_age_goods",
    "special_goods",
    "guild_goods",
    # Units (were in WEIGHTABLE_COLUMNS but not scoring — now score)
    "rogues",
    "fast_units",
    "heavy_units",
    "ranged_units",
    "artillery_units",
    "light_units",
    "next_age_fast_units",
    "next_age_heavy_units",
    "next_age_ranged_units",
    "next_age_artillery_units",
    "next_age_light_units",
    # Population (signed: negative values penalise high-consumption buildings)
    "Population",
    # Army boosts
    "Red Attack",
    "Red Defense",
    "Blue Attack",
    "Blue Defense",
    "Red GBG Attack",
    "Red GBG Defense",
    "Blue GBG Attack",
    "Blue GBG Defense",
    "Red GE Attack",
    "Red GE Defense",
    "Blue GE Attack",
    "Blue GE Defense",
    "Red QI Attack",
    "Red QI Defense",
    "Blue QI Attack",
    "Blue QI Defense",
    "QI Coin at start",
    "QI Supplies at start",
    "QI Goods at start",
    "QI Units at start",
    "QA per hour",
    "QA Capacity",
    "finish_special_production",
    "Coin %",
    "Supplies %",
    "Medal Boost",
]

# Maps a building's percentage-boost column to the production column(s) it amplifies.
# Used by _apply_context_boosts to convert boost% into equivalent production units.
# "Goods Boost" maps to a LIST because it applies to all three age tiers simultaneously;
# all other boosts target a single column.
BOOST_TO_BASE_MAPPING = {
    "FP boost": "forge_points",
    "Goods Boost": ["goods", "prev_age_goods", "next_age_goods"],
    "Guild Goods Production %": "guild_goods",
    "Special Goods Production %": "special_goods",
}

# Multiplier applied to C1 normalised scores before display.
# Scales 0.0278 → 2.78, making scores more legible without changing rankings.
C1_SCORE_MULTIPLIER = 100

# User context configuration for multiplicative metrics
USER_CONTEXT_FIELDS = {
    "fp_daily_production": {
        "label_key": "fp_daily_production_label",
        "help_key": "fp_daily_production_help",
        "default": 0,
        "related_boosts": ["FP boost"],
    },
    "goods_current_production": {
        "label_key": "goods_current_production_label",
        "help_key": "goods_current_production_help",
        "default": 0,
        "related_boosts": ["Goods Boost"],
    },
    "goods_previous_production": {
        "label_key": "goods_previous_production_label",
        "help_key": "goods_previous_production_help",
        "default": 0,
        "related_boosts": ["Goods Boost"],
    },
    "goods_next_production": {
        "label_key": "goods_next_production_label",
        "help_key": "goods_next_production_help",
        "default": 0,
        "related_boosts": ["Goods Boost"],
    },
    "guild_goods_production": {
        "label_key": "guild_goods_production_label",
        "help_key": "guild_goods_production_help",
        "default": 0,
        "related_boosts": ["Guild Goods Production %"],
    },
    "special_goods_production": {
        "label_key": "special_goods_production_label",
        "help_key": "special_goods_production_help",
        "default": 0,
        "related_boosts": ["Special Goods Production %"],
    },
}

# User current boost percentages configuration
USER_BOOST_FIELDS = {
    "current_fp_boost": {
        "label_key": "current_fp_boost_label",
        "help_key": "current_fp_boost_help",
        "default": 0.0,
        "related_context": "fp_daily_production",
    },
    "current_goods_boost": {
        "label_key": "current_goods_boost_label",
        "help_key": "current_goods_boost_help",
        "default": 0.0,
        "related_context": [
            "goods_current_production",
            "goods_previous_production",
            "goods_next_production",
        ],
    },
    "current_guild_goods_boost": {
        "label_key": "current_guild_goods_boost_label",
        "help_key": "current_guild_goods_boost_help",
        "default": 0.0,
        "related_context": "guild_goods_production",
    },
    "current_special_goods_boost": {
        "label_key": "current_special_goods_boost_label",
        "help_key": "current_special_goods_boost_help",
        "default": 0.0,
        "related_context": "special_goods_production",
    },
}

# Points awarded per unit of resource, used by city_analysis.py to rank owned buildings.
# "forge_points" is a single scalar (same value at every era).
# "goods" values are era-scaled: higher eras produce rarer goods worth more ranking points.
# "special_goods" only has entries for the eras where special goods actually exist in-game
# (Arctic Future, Oceanic Future, and the six Space Ages); all other eras have no special goods.
RANKING_POINTS_PER_RESOURCE = {
    "forge_points": 15,
    "goods": {
        "SpaceAgeSpaceHub": 69,
        "SpaceAgeTitan": 63,
        "SpaceAgeJupiterMoon": 55,
        "SpaceAgeVenus": 49.5,
        "SpaceAgeAsteroidBelt": 44.5,
        "SpaceAgeMars": 37.5,
        "VirtualFuture": 33,
        "OceanicFuture": 29,
        "ArcticFuture": 22.5,
        "FutureEra": 21,
        "TomorrowEra": 19.5,
        "ContemporaryEra": 13.5,
        "PostModernEra": 12.5,
        "ModernEra": 11.5,
        "ProgressiveEra": 6,
        "IndustrialAge": 5.5,
        "ColonialAge": 5,
        "LateMiddleAge": 4.5,
        "HighMiddleAge": 4,
        "EarlyMiddleAge": 3.5,
        "IronAge": 3,
        "BronzeAge": 2.5,
    },
    "special_goods": {
        "SpaceAgeSpaceHub": 10,
        "SpaceAgeTitan": 10,
        "SpaceAgeJupiterMoon": 10,
        "SpaceAgeVenus": 10,
        "SpaceAgeAsteroidBelt": 10,
        "SpaceAgeMars": 10,
        "OceanicFuture": 42,
        "ArcticFuture": 42,
    },
}

WEIGHT_PRESETS = {
    "player_ranking_points": {
        "weights": {
            "forge_points": 15,
            "goods": 69,
            "next_age_goods": 69,
            "prev_age_goods": 63,
            "special_goods": 10,
            "guild_goods": 69,
        },
        "mode": "classic",
        "help": "Focus on ranking points",
    },
    "well_rounded_farmer": {
        "weights": {
            "forge_points": 1,
            "forgepoint_package": 0.2,  # Less important than actual FPs because cannot be boosted by FP boosts
            "goods": 1,
            "next_age_goods": 1,
            "prev_age_goods": 1,
            "special_goods": 0.5,  # Usually less important than actual goods because you only need them for technologies (or CoCa in SASH but it's 1 in 7 chance to obtain one)
            "guild_goods": 0.2,  # Usually less important, most players produce enough to sustain their own cost nowadays.
            "coins": 0.1,
            "supplies": 0.15,
            "medals": 0.01,
            "Red Attack": 0.2,
            "Red Defense": 0.15,
            "Blue Attack": 0.2,
            "Blue Defense": 0.15,
            "Red GBG Attack": 0.2,
            "Red GBG Defense": 0.15,
            "Blue GBG Attack": 0.2,
            "Blue GBG Defense": 0.15,
            "Red GE Attack": 0.1,
            "Red GE Defense": 0.05,
            "Blue GE Attack": 0.1,
            "Blue GE Defense": 0.05,
            "Red QI Attack": 0.2,
            "Red QI Defense": 0.15,
            "Blue QI Attack": 0.2,
            "Blue QI Defense": 0.15,
            "rogues": 0.8,
            "fast_units": 0.1,
            "heavy_units": 0.1,
            "ranged_units": 0.1,
            "artillery_units": 0.1,
            "light_units": 0.1,
            "next_age_fast_units": 0.1,
            "next_age_heavy_units": 0.1,
            "next_age_ranged_units": 0.1,
            "next_age_artillery_units": 0.1,
            "next_age_light_units": 0.1,
        },
        "mode": "normalised",
        "help": "Well-rounded player with a farming focus (Main focus on FP/Goods, slight focus on GBG/GE bonuses, slight focus on QI fighting stats, no focus on QI start bonuses or QA production or capacity)",
    },
    "well_rounded_fighter": {
        "weights": {
            "forge_points": 0.2,
            "forgepoint_package": 0.05,  # Less important than actual FPs because cannot be boosted by FP boosts
            "goods": 0.2,
            "next_age_goods": 0.2,
            "prev_age_goods": 0.2,
            "special_goods": 0.05,  # Usually less important than actual goods because you only need them for technologies (or CoCa in SASH but it's 1 in 7 chance to obtain one)
            "guild_goods": 0.1,  # Usually less important, most players produce enough to sustain their own cost nowadays.
            "coins": 0.05,
            "supplies": 0.05,
            "medals": 0.01,
            "Red Attack": 1,
            "Red Defense": 0.8,
            "Blue Attack": 1,
            "Blue Defense": 0.8,
            "Red GBG Attack": 1,
            "Red GBG Defense": 0.8,
            "Blue GBG Attack": 1,
            "Blue GBG Defense": 0.8,
            "Red GE Attack": 0.25,
            "Red GE Defense": 0.1,
            "Blue GE Attack": 0.25,
            "Blue GE Defense": 0.1,
            "Red QI Attack": 0.5,
            "Red QI Defense": 0.25,
            "Blue QI Attack": 0.5,
            "Blue QI Defense": 0.25,
            "rogues": 0.8,
            "fast_units": 0.3,
            "heavy_units": 0.3,
            "ranged_units": 0.3,
            "artillery_units": 0.3,
            "light_units": 0.3,
            "next_age_fast_units": 0.3,
            "next_age_heavy_units": 0.3,
            "next_age_ranged_units": 0.3,
            "next_age_artillery_units": 0.3,
            "next_age_light_units": 0.3,
        },
        "mode": "normalised",
        "help": "Well-rounded player with a fighting focus (Main focus on Red/Blue att/def (both normal and GBG), slight focus on GE bonuses, slight focus on QI fighting stats, no focus on QI start bonuses or QA production or capacity)",
    },
    "fp_focused_farmer_no_fighting": {
        "weights": {
            "forge_points": 1,
            "forgepoint_package": 0.3,  # Less important than actual FPs because cannot be boosted by FP boosts
            "goods": 0.5,
            "next_age_goods": 0.5,
            "prev_age_goods": 0.5,
            "guild_goods": 0.2,
            "coins": 0.01,
            "supplies": 0.015,
        },
        "mode": "normalised",
        "help": "Farmer (FP-focused with no fighting stats focus)",
    },
    "GBG_fighter_no_farm_focus": {
        "weights": {
            "Red Attack": 1,
            "Red Defense": 0.8,
            "Blue Attack": 1,
            "Blue Defense": 0.8,
            "Red GBG Attack": 1,
            "Red GBG Defense": 0.8,
            "Blue GBG Attack": 1,
            "Blue GBG Defense": 0.8,
            "rogues": 0.8,
            "fast_units": 0.1,
            "heavy_units": 0.1,
            "ranged_units": 0.1,
            "artillery_units": 0.1,
            "light_units": 0.1,
            "next_age_fast_units": 0.1,
            "next_age_heavy_units": 0.1,
            "next_age_ranged_units": 0.1,
            "next_age_artillery_units": 0.1,
            "next_age_light_units": 0.1,
        },
        "mode": "normalised",
        "help": "GBG Only",
    },
}
